apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificataion-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notificataion
  template:
    metadata:
      labels:
        app: notificataion
    spec:
      containers:
        - name: notificataion-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/notification-service:cb1003fe53c652959fa5fc50fa811f607d38ac51
          ports:
            - containerPort: 4006
