apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      serviceAccountName: catalog-service-sa
      containers:
        - name: catalog-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/catalog-service:06b3846e9cf7d9a3cc5a513ca75912967f8254c5
          ports:
            - containerPort: 4002
          env:
            - name: DB_SECRET_ARN
              value: "arn:aws:secretsmanager:us-east-1:463623100443:secret:rds!db-1a6c74a2-c1c7-496d-83ca-386c7068db12-P9f5QL"
            - name: DB_HOST
              value: "productdb-dev.ca3yoec4ecx8.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "productdb"
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: "regional"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
