apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/catalog-service:155c7080a280d365441be2585919f708b87e768d
          ports:
            - containerPort: 4002
