#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      serviceAccountName: catalog-service-sa
      containers:
        - name: catalog-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/catalog-service:05afc7ef3f0295db89383eda192b8ae040caa426
          ports:
            - containerPort: 4002
          env:
            - name: DB_SECRET_ARN
              value: "xxxxxxxxxxxxxxxxxxxxxcret:rds!db-93dxxxxxxxxxxxxxxxxx31-c59201a5c884-kkaxtP"
            - name: DB_HOST
              value: "xxxxxxxxxxxxxxxxxx1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "productdb"
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: "regional"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_REGION
              value: "us-east-1"
            - name: S3_BUCKET_NAME
              value: "ecom-product-images-test-bucket"
