#
apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "0"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded,HookFailed
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: catalog-service-sa
      containers:
        - name: migrate
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/catalog-service:05afc7ef3f0295db89383eda192b8ae040caa426
          command: ["node", "migrate.js"]
          env:
            - name: DB_SECRET_ARN
              value: "arn:aws:secretsmanager:us-east-1:463623100443:secret:rds!db-93dd91fc-ba37-4d9f-9a31-c59201a5c884-kkaxtP"
            - name: DB_HOST
              value: "productdb-dev.ca3yoec4ecx8.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "productdb"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
