apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: catalog-service-sa
      containers:
        - name: migrate
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/catalog-service:a0896d019b432311f8c1059d44540e4a6424f351
          command: ["npx", "knex", "migrate:latest"]
          env:
            - name: DB_SECRET_ARN
              value: "arn:aws:secretsmanager:us-east-1:463623100443:secret:rds!db-1a6c74a2-c1c7-496d-83ca-386c7068db12-P9f5QL"
            - name: DB_HOST
              value: "productdb-dev.ca3yoec4ecx8.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "productdb"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"