#
apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "0"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded,HookFailed
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: catalog-service-sa
      containers:
        - name: migrate
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/catalog-service:7d1895474ab83fc04c802a5c915fd35ef29f93e0
          command: ["node", "migrate.js"]
          env:
            - name: DB_SECRET_ARN
              value: "arn:aws:secretsmanager:us-east-1:463623100443:secret:rds!db-c425e51b-5205-4836-ab89-4e9231206ef3-AQGJxz"
            - name: DB_HOST
              value: "productdb-dev.ca3yoec4ecx8.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "productdb"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
