apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/cart-service:b9ab7c5dbb1d80c59f2d2090b0558d0079d6a2c5
          ports:
            - containerPort: 4003
