apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/order-service:727988134a3f8a80128ee6ee8a7bf1865f0a9ab1
          ports:
            - containerPort: 4004
