apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/order-service:29d35a197250794eef6d817022f36000a52a7740
          ports:
            - containerPort: 4004
