apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/order-service:4cfa3550ca6267cf2f7cce3b5bcff752c2dc2ff5
          ports:
            - containerPort: 4004
