#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::463623100443:role/auth-db-secret-read
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-1"