apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/auth-service:6769ebf6e2fed2972141d3f2a4a4c6ca7b61b6e9
          ports:
            - containerPort: 4001
