#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: auth-service-sa
      containers:
        - name: auth-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/auth-service:575eb78f2ead6ea5108f7cde116a705137448bba
          ports:
            - containerPort: 4001
          env:
            - name: DB_SECRET_ARN
              value: "arn:aws:secretsmanager:us-east-1:463623100443:secret:rds!db-c4f51d83-995f-42d7-9f11-b4b46f22c6f2-khAmMl"
            - name: DB_HOST
              value: "authdb-dev.ca3yoec4ecx8.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "authdb"
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: "regional"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
