apiVersion: batch/v1
kind: Job
metadata:
  name: auth-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "0"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: auth-service-sa
      containers:
        - name: migrate
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/auth-service:008acef484532cb47d0bc6a4fd2dac7920c74ad4
          command: ["node", "migrate.js"]
          env:
            - name: DB_SECRET_ARN
              value: "arn:aws:secretsmanager:us-east-1:463623100443:secret:rds!db-f38b029e-dbbd-410f-a608-9816fd043678-VR03Cl"
            - name: DB_HOST
              value: "authdb-dev.ca3yoec4ecx8.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "authdb"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
