#
apiVersion: batch/v1
kind: Job
metadata:
  name: auth-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "0"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded,HookFailed
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: auth-service-sa
      containers:
        - name: migrate
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/auth-service:f59441604f8b75d073b74b41a81ce11854d72782
          command: ["node", "migrate.js"]
          env:
            - name: DB_SECRET_ARN
              value: "xxxxxxxxxxxxxxxxxxxxxxxxxxMl"
            - name: DB_HOST
              value: "xxxxxxxxxxxxxxxx-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5xx2"
            - name: DB_NAME
              value: "authdb"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
