apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/payment-service:4cfa3550ca6267cf2f7cce3b5bcff752c2dc2ff5
          ports:
            - containerPort: 4005
