apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment-service
          image: 463623100443.dkr.ecr.us-east-1.amazonaws.com/payment-service:addb97d75f1fddb19559442eddd6ec5c4f4927dc
          ports:
            - containerPort: 4005
